/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/error/404': RouteRecordInfo<'/error/404', '/error/404', Record<never, never>, Record<never, never>>,
    '/front/Detail': RouteRecordInfo<'/front/Detail', '/front/Detail', Record<never, never>, Record<never, never>>,
    '/front/Goods': RouteRecordInfo<'/front/Goods', '/front/Goods', Record<never, never>, Record<never, never>>,
    '/front/Home': RouteRecordInfo<'/front/Home', '/front/Home', Record<never, never>, Record<never, never>>,
    '/front/Notice': RouteRecordInfo<'/front/Notice', '/front/Notice', Record<never, never>, Record<never, never>>,
    '/front/Publish': RouteRecordInfo<'/front/Publish', '/front/Publish', Record<never, never>, Record<never, never>>,
    '/front/UserInfo': RouteRecordInfo<'/front/UserInfo', '/front/UserInfo', Record<never, never>, Record<never, never>>,
    '/front/Wanted': RouteRecordInfo<'/front/Wanted', '/front/Wanted', Record<never, never>, Record<never, never>>,
    '/Login/': RouteRecordInfo<'/Login/', '/Login', Record<never, never>, Record<never, never>>,
  }
}
